# Generated by Django 3.1.2 on 2020-10-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201022_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imgage',
            new_name='image',
        ),
    ]
